server:
  port: 8080

spring:
  application:
    name: spring-batch-skelton
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./batch
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  batch:
    jdbc:
      initialize-schema: always
